export const themes = {
  light: {
    colorBgBase: "white",
    colorPrimary: "black",
    colorTextBase: "black",
    bodyBg: "#f9f9f9",
    headerBg: "white",
    headerColor: "black",
    colorBgContainer: "white",
    colorBgElevated: "white",
    fontFamily: "Nunito Sans",
    buttonBackground: "white",
    searchIconColor: "#bbbbbb",
    controlItemBgActive: "#c6c6c6",
    controlItemBgActiveHover: "#c6c6c6",
    controlItemBgHover: "#c6c6c6",
    headerHeight: 80,
  },
  dark: {
    colorBgBase: "#1d282f",
    colorPrimary: "white",
    colorTextBase: "white",
    bodyBg: "#1d282f",
    headerBg: "#26303b",
    headerColor: "white",
    colorBgContainer: "#26303b",
    colorBgElevated: "#26303b",
    colorTextQuaternary: "white",
    fontFamily: "Nunito Sans",
    buttonBackground: "#26303b",
    searchIconColor: "white",
    controlItemBgActive: "#576e87",
    controlItemBgActiveHover: "#576e87",
    controlItemBgHover: "#576e87",
    headerHeight: 80,
  },
};

export type Theme = typeof themes.light;
